services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=anhthing
      - POSTGRES_PASSWORD=Ng5509
      - POSTGRES_DB=anhthing-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '8000:5432'

volumes:
  postgres-data:
